apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA==
#  mysql-database: gmforge
  mysql-database: Z21mb3JnZQ==
  jwt-secret: R01GT1JHRV9TdXBlclNQZWNpYWxrZXlfMjAyNg==