apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA==
#  mysql-database: gmforge
  mysql-database: Z21mb3JnZQ==
  jwt-secret: Z21mb3JnZV9qd3Rfc2VjcmV0X2tsdWN6XzIwMjRfYWJj
