spring.application.name=backend

#Database properties
spring.datasource.url=jdbc:mysql://localhost:3306/gmforge
#spring.datasource.url=jdbc:mysql://mysql-service:3306/gmforge
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Secret key
jwt.secret=${JWT_SECRET:eLUCO2EJtn1ZQJz4JSNsz9lFYPWT18sxIqKbeRlkD2A}